name: Register Discord Slash Commands

on:
  workflow_dispatch:  # Allows you to run it manually in the Actions tab

jobs:
  register:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run slash command registration
        run: npx tsx register-commands.ts
